server:
    port: 8282
spring:
    datasource:
        password: root
        platform: postgres
        url: jdbc:postgresql://localhost:5432/ClanCloudyPOSV1
        username: postgres
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect                
        show-sql: true   
        open-in-view: true
